version: '3.3'
services:
  mongo_db:
    image: mongo:3.2

    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    # build: ./ui
    image: ${D_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    command: puma -w 2 --debug
    networks:
      - frontend
  post:
    # build: ./post-py
    image: ${D_USERNAME}/post:${POST_TAG}
    environment:
    - POST_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend
  comment:
    # build: ./comment
    image: ${D_USERNAME}/comment:${COMMENT_TAG}
    environment:
    - COMMENT_DATABASE_HOST=mongo_db
    command: puma -w 2 --debug
    networks:
      - frontend
      - backend

volumes:
  post_db:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
